# Generated by Django 3.2.9 on 2023-10-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_fooditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
