# Generated by Django 3.2.9 on 2023-10-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_estimated_delivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food',
            new_name='items',
        ),
    ]
