from django.urls import path
from rest_framework.routers import DefaultRouter

from .views.menu import FoodItemViewSet
from .views.order import OrderViewSet
from .views.restaurant import RestaurantViewSet, RestaurantMenu

# Create a router and register the ViewSet with it
router = DefaultRouter()
router.register(r'menu', FoodItemViewSet, basename='menu')
router.register(r'orders', OrderViewSet, basename='order')
router.register(r'restaurants', RestaurantViewSet, basename='restaurant')

# The DefaultRouter generates URL patterns for the ViewSet
urlpatterns = [
    path('restaurants/<int:pk>/menu/', RestaurantMenu.as_view(), name='restaurant-menu'),
]

# Extend the URL patterns by including the ones generated by the router
urlpatterns += router.urls
