from django.urls import path
from rest_framework.routers import DefaultRouter

from .views.menu import FoodItemViewSet
from .views.order import OrderViewSet

# Create a router and register the ViewSet with it
router = DefaultRouter()
router.register(r'menu', FoodItemViewSet, basename='menu')
router.register(r'orders', OrderViewSet, basename='order')

# The DefaultRouter generates URL patterns for the ViewSet
urlpatterns = [
    # Other URL patterns for your project if needed
]

# Extend the URL patterns by including the ones generated by the router
urlpatterns += router.urls
